/**
 * NAVEGACAO UNICA — fonte única de verdade dos menus do Panorama.
 * O header (PanoramaHeader) e a lateral (PanoramaSideMenu) leem ESTA lista,
 * eliminando a duplicação de links entre os dois menus.
 * SOMENTE dados de navegação — nenhuma função, cálculo ou dado do sistema.
 */
import {
  Scale,
  Factory,
  ShoppingBasket,
  ShieldCheck,
  Percent,
  Layers,
  Paperclip,
  CalendarDays,
  Database,
  Globe2,
  ListChecks,
  History,
  Home,
  Tractor,
  Handshake,
  Landmark,
  Smartphone,
  Printer,
  KeyRound,
  MonitorSmartphone,
} from 'lucide-react'

export interface LinkNavegacao {
  href: string
  label: string
  tecla: string
  numero?: string
  Icon: React.ComponentType<{ className?: string }>
  cor: string
  bg: string
  borda: string
}

export const NAVEGACAO: LinkNavegacao[] = [
  {
    href: '#secao-1',
    label: 'Normas',
    tecla: '1',
    numero: '1',
    Icon: Scale,
    cor: 'text-indigo-600',
    bg: 'bg-indigo-50',
    borda: 'border-indigo-200',
  },
  {
    href: '#secao-2',
    label: 'Fato Gerador',
    tecla: '2',
    numero: '2',
    Icon: Factory,
    cor: 'text-blue-600',
    bg: 'bg-blue-50',
    borda: 'border-blue-200',
  },
  {
    href: '#secao-3',
    label: 'Cesta Básica',
    tecla: '3',
    numero: '3',
    Icon: ShoppingBasket,
    cor: 'text-emerald-600',
    bg: 'bg-emerald-50',
    borda: 'border-emerald-200',
  },
  {
    href: '#secao-4',
    label: 'Imunidades',
    tecla: '4',
    numero: '4',
    Icon: ShieldCheck,
    cor: 'text-teal-600',
    bg: 'bg-teal-50',
    borda: 'border-teal-200',
  },
  {
    href: '#secao-5',
    label: 'Isenções e Alíquotas',
    tecla: '5',
    numero: '5',
    Icon: Percent,
    cor: 'text-amber-600',
    bg: 'bg-amber-50',
    borda: 'border-amber-200',
  },
  {
    href: '#secao-6',
    label: 'Regimes Específicos',
    tecla: '6',
    numero: '6',
    Icon: Layers,
    cor: 'text-orange-600',
    bg: 'bg-orange-50',
    borda: 'border-orange-200',
  },
  {
    href: '#regime-imobiliario',
    label: 'Regime Imobiliário',
    tecla: 'i',
    numero: '6A',
    Icon: Home,
    cor: 'text-amber-700',
    bg: 'bg-amber-50',
    borda: 'border-amber-200',
  },
  {
    href: '#agronegocio',
    label: 'Agronegócio',
    tecla: 'g',
    numero: '6B',
    Icon: Tractor,
    cor: 'text-emerald-700',
    bg: 'bg-emerald-50',
    borda: 'border-emerald-200',
  },
  {
    href: '#consorcios',
    label: 'Consórcios',
    tecla: 'c',
    numero: '6C',
    Icon: Handshake,
    cor: 'text-violet-700',
    bg: 'bg-violet-50',
    borda: 'border-violet-200',
  },
  {
    href: '#financeiros',
    label: 'Financeiros',
    tecla: 'f',
    numero: '6D',
    Icon: Landmark,
    cor: 'text-violet-700',
    bg: 'bg-violet-50',
    borda: 'border-violet-200',
  },
  {
    href: '#simples',
    label: 'Simples Nacional',
    tecla: 'p',
    numero: '6E',
    Icon: Percent,
    cor: 'text-blue-700',
    bg: 'bg-blue-50',
    borda: 'border-blue-200',
  },
  {
    href: '#profissionais-plataformas',
    label: 'Profissionais e Plataformas',
    tecla: 'r',
    numero: '6F',
    Icon: Smartphone,
    cor: 'text-indigo-700',
    bg: 'bg-indigo-50',
    borda: 'border-indigo-200',
  },
  {
    href: '#secao-7',
    label: 'Anexos',
    tecla: '7',
    numero: '7',
    Icon: Paperclip,
    cor: 'text-rose-600',
    bg: 'bg-rose-50',
    borda: 'border-rose-200',
  },
  {
    href: '#tabela-geral',
    label: 'Tabela Geral dos Anexos',
    tecla: 'a',
    numero: '7A',
    Icon: CalendarDays,
    cor: 'text-rose-700',
    bg: 'bg-rose-100',
    borda: 'border-rose-300',
  },
  {
    href: '#secao-8',
    label: 'Cronograma 2026–2033',
    tecla: '8',
    numero: '8',
    Icon: CalendarDays,
    cor: 'text-cyan-600',
    bg: 'bg-cyan-50',
    borda: 'border-cyan-200',
  },
  {
    href: '#secao-9',
    label: 'Fontes & Atualização',
    tecla: '9',
    numero: '9',
    Icon: Database,
    cor: 'text-violet-600',
    bg: 'bg-violet-50',
    borda: 'border-violet-200',
  },
  {
    href: '#fontes-agregador',
    label: 'Agregadores (Buscador NCM)',
    tecla: 'q',
    numero: '11',
    Icon: Globe2,
    cor: 'text-sky-600',
    bg: 'bg-sky-50',
    borda: 'border-sky-200',
  },
  {
    href: '#fontes-primarias',
    label: 'Fontes primárias (110 bases)',
    tecla: 'w',
    numero: '12',
    Icon: ListChecks,
    cor: 'text-fuchsia-600',
    bg: 'bg-fuchsia-50',
    borda: 'border-fuchsia-200',
  },
  {
    href: '#central-entrega',
    label: 'Central de Entrega (imprimir/enviar)',
    tecla: 'e',
    numero: '14',
    Icon: Printer,
    cor: 'text-rose-600',
    bg: 'bg-rose-50',
    borda: 'border-rose-200',
  },
  {
    href: '#assistentes-seguranca',
    label: 'Assistentes & Segurança',
    tecla: 'x',
    numero: '15',
    Icon: ShieldCheck,
    cor: 'text-indigo-600',
    bg: 'bg-indigo-50',
    borda: 'border-indigo-200',
  },
  {
    href: '#controle-acesso',
    label: 'Níveis de Acesso (CRUD)',
    tecla: 'l',
    numero: '16',
    Icon: KeyRound,
    cor: 'text-amber-700',
    bg: 'bg-amber-50',
    borda: 'border-amber-300',
  },
  {
    href: '#responsividade-celulares',
    label: 'Responsividade em Celulares',
    tecla: 'm',
    numero: '17',
    Icon: MonitorSmartphone,
    cor: 'text-cyan-700',
    bg: 'bg-cyan-50',
    borda: 'border-cyan-300',
  },
  {
    href: '#historico-atualizacoes',
    label: 'Histórico de Atualizações',
    tecla: 'h',
    numero: '13',
    Icon: History,
    cor: 'text-lime-600',
    bg: 'bg-lime-50',
    borda: 'border-lime-200',
  },
]
